update execute script to return the string result and added scrollToP…
cloudinary/wdio-allure-ts pull request #184
Opened 2020-12-06 09:26 UTC by refael-m

as part of [APPS-6231](https://cloudinary.atlassian.net/browse/APPS-6231)

2020-12-06 10:11 UTC, FelixZilber requested changes

2020-12-06 10:11 UTC, FelixZilber commented on src/commons/BrowserUtils.ts
> +  export function scrollToPixels(selector: string, x: number, y: number): void {
please add tests

2020-12-06 10:11 UTC, FelixZilber commented on src/commons/BrowserUtils.ts
> +    return tryBlock(() => browser.execute(script), `Failed to execute script: ${script}`);
add test for this change

2020-12-06 14:19 UTC, refael-m commented on src/commons/BrowserUtils.ts
> +  export function scrollToPixels(selector: string, x: number, y: number): void {
added

2020-12-06 14:19 UTC, refael-m commented on src/commons/BrowserUtils.ts
> +    return tryBlock(() => browser.execute(script), `Failed to execute script: ${script}`);
added

2020-12-06 18:51 UTC, FelixZilber requested changes

2020-12-06 18:51 UTC, FelixZilber commented on src/test/specs/ScrollToPixels.ts
> +describeCommon('ScrollToPixels', () => {
the file name must end with 'Spec.ts'

2020-12-07 08:03 UTC, refael-m commented on src/test/specs/ScrollToPixels.ts
> +describeCommon('ScrollToPixels', () => {
done

2020-12-07 08:39 UTC, FelixZilber requested changes

2020-12-07 08:39 UTC, FelixZilber commented on src/commons/BrowserUtils.ts
> +  export function scrollToPixels(selector: string, x: number, y: number): void {
suggest changing the name to "scrollTo"

2020-12-07 09:08 UTC, FelixZilber approved these changes

2020-12-07 10:46 UTC, merged