fix: fixing isDisplayedInViewportSpec
cloudinary/wdio-allure-ts pull request #319
Opened 2022-11-15 09:43 UTC by ntatuani-cloudinary

## Brief Summary of Changes
-

## Reviewer, Please Note:
-

## Testing (what was tested)
-

2022-11-15 10:43 UTC, FelixZilber commented on src/commons/BrowserUtils.ts
> +    // await tryBlock(async () => $(selector).isDisplayedInViewport(), '${selector} not found in the viewport');
please remove

2022-11-15 10:44 UTC, FelixZilber commented on src/test/specs/isDisplayedInViewportSpec.ts
> +    chai.expect(await BrowserUtils.isDisplayedInViewport(notExistSelector)).to.be.false;
notExist is not the same as not in view port...

2022-11-15 10:45 UTC, FelixZilber requested changes
see comments inline

2022-11-22 09:22 UTC, FelixZilber commented
@ntatuani-cloudinary any updates regarding this one?

2022-12-01 12:50 UTC, ntatuani-cloudinary commented
testnow

2022-12-01 13:50 UTC, FelixZilber approved these changes

2022-12-01 13:51 UTC, merged